### ISSUE TITLE
Abstract / Introduction

### ISSUE THREAD

**Issue by bugwelle** [fidsusj/SWE-Seminar#2]
_TODO_

**Comment by MaxEdinger** [comment]
@JulianStudent: Abstract (komplett), Englisch und Deutsch

**Comment by MaxEdinger** [comment]
@bugwelle Introduction (1/2) Fragen 1-3, inhaltlicher Teil, Problemstellung, Interesse wecken, kurz auf die Artikel eingehen

**Comment by MaxEdinger** [comment]
@MaxEdinger Introduction(2/2) Frage 4, formaler Teil, wichtigste Begriffe einführen, auf Glosssar und SWEBOK verweisen, Synthesefragen auflisten, MovieManager Bsp Anforderungen auflisten (DONE)

**Comment by bugwelle** [comment]
Ist alles soweit erledigt.
